org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=runeveilcrates
mod_name=RuneVeil Crates
mod_license=MIT
mod_version=1.3.3
mod_group_id=com.runeveil.crates
mod_authors=RuneVeil
mod_description=Server-side vote, donor, event, and Discord Nitro crate keys with holograms and a loot editor.
